 
apiVersion: backstage.io/v1alpha1
kind: API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $text: ./openapi.yaml
metadata:
  name: "my-app-api"
--- 
apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: application
  lifecycle: production
  owner: user:guest
  providesApis:
  - "my-app-api"
metadata:
  name: "my-app"
  labels:
    app.kubernetes.io/name: "my-app"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
    app.quarkus.io/version: 3.17.3
  annotations:
    backstage.io/source-location: "url:https://github.com/iocanel/my-app"
  tags:
  - java
  - quarkus
